### ISSUE TITLE
Januar 2016

### ISSUE THREAD

**Issue by meaku** [web-and-wine/meetups#11]
Wir brauchen einen Termin für Januar. Damit's nicht zu unerwartet kommt, lieber später im Januar an einem Dienstag. 
- 19. 
- 26. 

Wenn niemand was gegen den 26. einzuwenden hat, würde ich den Termin vorziehen da wir mehr Vorlaufzeit haben.

Wie siehts bei euch speakern aus? 
@pichfl @moritzjacobs

**Comment by MartinKolb1987** [comment]
Also meiner Meinung nach ist der 19. auch gut. 
Sind ja noch drei Wochen bis dahin.

**Comment by pichfl** [comment]
Der 19. ist schlecht, muss am 20. sehr früh morgens in Hamburg sein.

**Comment by moritzjacobs** [comment]
Sollen mir beide Recht sein, den Talk könnte ich auch halten. Wo findet es denn diesmal statt?

**Comment by MartinKolb1987** [comment]
Na dann lasst uns doch den 26. nehmen. Standorttechnisch bin ich noch uninformiert... werden wir aber abklären.

**Comment by zalvus** [comment]
Bei mir spricht nichts gegen den 26. :)

**Comment by Blacklist** [comment]
Bei mir spricht nichts gegen den 26. :)
