### ISSUE TITLE
Juni 2015 - Team23 

### ISSUE THREAD

**Issue by meaku** [web-and-wine/meetups#3]
Termin noch offen.

**Comment by meaku** [comment]
> Hallo Michael,
> 
> wir sind da relativ flexibel.
> Lediglich Webinale und DjangoCon machen
> die ersten beiden Dienstag schwierig.
> Gut passen würde es am 16.6 und 30.6.
> 
> Grüße Fabian

Wie sieht's da bei euch aus @Blacklist @MartinKolb1987

**Comment by MartinKolb1987** [comment]
Von meiner Seite aus gut. Ich würde den 16.06. anpeilen.
