### ISSUE TITLE
Juli 2015

### ISSUE THREAD

**Issue by meaku** [web-and-wine/meetups#4]
- aiti Park Grillen! 
- Wann habt ihr Zeit @Blacklist @MartinKolb1987 @Fannon?

**Comment by MartinKolb1987** [comment]
14.07./15.07. ?

**Comment by meaku** [comment]
Da ist's bei mir leider eher schlecht. Die zwei Wochen drauf würden beiden Dienstage gehen.

**Comment by Blacklist** [comment]
Same here. Aber Grillen wär schon lässig :D

**Comment by MartinKolb1987** [comment]
Wie wäre es dann mit dem 28.07. ? Dann ist die Sommerpause nicht ganz so lang ;-)

**Comment by meaku** [comment]
Aber da sind vielleicht schon einige im Urlaub. Passt euch der 21.?

**Comment by MartinKolb1987** [comment]
Okay, daran hab ich jetzt nicht gedacht ;-). 21. sollte bei mir auch passen.
