### ISSUE TITLE
Oktober 2015

### ISSUE THREAD

**Issue by meaku** [web-and-wine/meetups#5]
Chris Höfle hat uns geschrieben und XITASO als Location angeboten. Denk das wäre sehr cool für September. 

> Servus! Ich war gestern bei Web&Wine beim Team23 und fands sehr cool. Wie siehts aus, habt ihr Bock, das mal in unseren Räumlichkeiten zu machen? Ich arbeite bei der XITASO, wir sitzen bei der Ballonfabrik, falls du die kennst. Viele Grüße, Chris
> 
> Und ich dachte sowieso eher an August/September...wenn ihr wollt könnte man das schon fix machen. Wir hätten auch schon 1, 2 interessante Themen beizusteuern...  Viele Grüße & einen schönen Tag, Chris

**Comment by MartinKolb1987** [comment]
Absolut. Ist immer lässig wenn sich neue Firmen finden :-). Allerdings würde ich persönlich den Oktober anpeilen. Juli = Grill-Feier, August & September = geschlossen, Oktober = starten wir wieder durch . Was denkt ihr?

**Comment by Blacklist** [comment]
Jop der Chris hat mich beim letzten Web&Wine darauf angesprochen. Er wollts nur noch abklären. Oktober klingt gut - dann kann sich jeder erholen und neue Themen sammeln :)

**Comment by xitasoappdev** [comment]
Jungs, wie siehts aus? Sollen wir den Oktober anpeilen für ein Web&Wine bei uns?

**Comment by meaku** [comment]
Jap! Wann würds denn passen?

**Comment by xitasoappdev** [comment]
Dienstag, 6. Oktober oder Mittwoch, 7. Oktober?

**Comment by meaku** [comment]
Bisher hatten wir meist Dienstag. Dann machen wir doch einfach wieder Dienstag wenn das so passt. Außer wir bekommen bis morgen ein Veto von irgendwem :)

**Comment by meaku** [comment]
Talks brauchen wir natürlich auch unbedingt... Jemand was in der Pipeline?

**Comment by meaku** [comment]
Wir haben jetzt bisher 2 Talks. Einen kriegen wir bestimmt noch. Ich hab mal announced, damit die Leute das noch rechtzeitig mitkriegen.

**Comment by machucarro** [comment]
Hi guys, I'm new around here but working in Xitaso since July so I'll gather all my courage and present you the Strongloop Framework from IBM on next meetup. If someone has something against it talk now or shut up forever! ;)

Cheers volks!

**Comment by xitasoappdev** [comment]
Hey Jungs,
- Dienstag, 6. Oktober passt für uns
- Wir kümmern uns um Getränke und Snacks
- Den 3. Vortrag, sofern das für euch alle passt, würde unser Kollege Manu (siehe oben) auf Englisch halten

Alles cool soweit? Ich freu mich schon drauf!

**Comment by mattiloh** [comment]
Unfortunately I can't make it to the meet up next week. But yeah: :+1: for Strongloop!

**Comment by meaku** [comment]
Alles cool! 

@machucarro sure! I'll add i to the agenda. Should all the talks be in englisch then?

**Comment by meaku** [comment]
And do you mean Loopback? Or is there a new thing?

**Comment by meaku** [comment]
@xitasoappdev wieviel Leute passen denn bei euch rein? Dann setz ich das Limit, damit wir ggf. ne Warteliste füllen können.

**Comment by xitasoappdev** [comment]
@meaku wir haben jetzt mal mit 30 - 35 Leuten geplant für die Verpflegung

**Comment by machucarro** [comment]
Hi guys! @meaku It is the loopback framework, and it will be an introduction. They just got acquired by IBM recently and as many in Xitaso still don't know much about Node I thought it could be an interesting theme. Actually I can try as well to make the talk in German (I've been working in German for two years before Xitaso) but my grammar is not very good and I feel more comfortable doing it in English. I understand anyway almost everything so there is no need to do the other talks in English :)

**Comment by meaku** [comment]
@machucarro if you have slides you can add them to https://github.com/web-and-wine/talks/blob/master/README.md. And if you have a twitter handle you could also add it.
