### ISSUE TITLE
JS CodeRetreat

### ISSUE THREAD

**Issue by mattiloh** [web-and-wine/meetups#8]
Ich war im Juni beim letzten JS CodeRetreat in München dabei (http://jscoderetreat.com/). War ziemlich interessant und spannend. Wir sollten das auch mal in Augsburg machen!

Hier steht, wie's funktioniert: http://jscoderetreat.com/howitworks.html

Haben da noch andere Interesse dran?

**Comment by meaku** [comment]
:+1: auf jedenfall!

**Comment by MartinKolb1987** [comment]
finde ich gut :+1:

**Comment by mattiloh** [comment]
Am 5. Dezember ist das nächste in München. Wir könnten parallel dazu eins in Augsburg veranstalten. Ist glaube ich generell die Idee, dass die JSCodeRetreats am selben Tag an verschiedenen Orten stattfinden.

Dann brauchen wir nur noch einen Ort. Irgendeine Idee? Bei uns im Büro ist es evtl. ein bisschen klein. Da haben wir 4 Arbeitsplätze, würde also für knapp 8 Leute reichen.

**Comment by meaku** [comment]
> Bei uns im Büro ist es evtl. ein bisschen klein. Da haben wir 4 Arbeitsplätze, würde also für knapp 8 Leute reichen.

Wäre doch gar nicht so schlecht für den Anfang? 

Wir können ja dann nächsten Mal eine andere Location suchen. Bei uns im Büro geht's auch immer, allerdings auch nur 15 - 20 Personen. Sonst steht uns der aitiRaum auch immer offen. 

Oder meinst du es bringt's nicht bei nur 8 Leuten?

**Comment by mattiloh** [comment]
8 wird übersichtlich, aber für einen ersten Start vielleicht gar nicht so schlecht. Können wir gerne bei uns im Büro machen. Lohnt sich da überhaupt eine Meetup-Veranstaltung mit Einladungen? Ich bin schon mal dabei, sind also noch 7 Plätze frei ;)

**Comment by meaku** [comment]
Willst du's beim nächsten Web&Wine kurz vorstellen? Dann können sich Interessenten direkt melden?
Ich wäre auch gern dabei :)

**Comment by matthaias** [comment]
Ich bin irgendwie nie da, wenn ein CodeRetreat is :(

**Comment by mattiloh** [comment]
Klar, stell ich kurz vor. Dann sind noch 6 Plätze frei. Wenn der Ansturm riesig ist, kann man ja den Ort verlegen.

**Comment by meaku** [comment]
Gute Idee. So machen wir's! Dann trag ich dich noch als "Lightning Talk" ein.

**Comment by mattiloh** [comment]
Ja, gerne. Wird nur 2 min. dauern.

**Comment by MartinKolb1987** [comment]
ich würde keinen L-Talk anlegen deswegen. Kann er einfach so kommunizieren :-)

**Comment by meaku** [comment]
Hab ich mir Anfangs auch gedacht, aber dann doch gemacht. Dann haben wir's offiziell auf der Agenda. Auch wenns nur 2 Minuten sind...

**Comment by MartinKolb1987** [comment]
Dann legen wir den Werbeblocker für Web&Wine-Tages-Event auch an?! :-D
